version: "3.8"
services:
  api-gateway:
    build: ./api
    container_name: microservices_container_api
    ports:
    - 8000:8000
    expose:
    - "8000"
    networks:
    - dev_network
    depends_on:
    - adminservices
    - customerservices
    # - googleservices
    # - miscservices
    # - notificationservices
    # - reportservices
    # - subscriptionservices
    - voucherservices
  adminservices:
    build: ./adminservices
    container_name: microservices_container_adminservices
    ports:
    - 8001:8001
    expose:
    - "8001"
    networks:
    - dev_network
    volumes:
      - ./adminservices:/adminservices
      - '/adminservices/node_modules'
    
  customerservices:
    build: ./customerservices
    container_name: reseller_admin_backend_customerservices
    ports:
    - 8002:8002
    expose:
    - "8002"
    networks:
    - dev_network
    volumes:
      - ./customerservices:/customerservices
      - '/customerservices/node_modules'
    
  # googleservices:
  #   build: ./googleservices
  #   container_name: microservices_container_googleservices
  #   ports:
  #     - "8003:8003"
  #   expose:
  #   - "8003"  
  #   networks:
  #     - dev_network

  # miscservices:
  #   build: ./miscservices
  #   container_name: microservices_container_miscservices
  #   ports:
  #     - "8004:8004"
  #   expose:
  #   - "8004"  
  #   networks:
  #     - dev_network

  # notificationservices:
  #   build: ./notificationservices
  #   container_name: microservices_container_notificationservices
  #   ports:
  #     - "8005:8005"
  #   expose:
  #   - "8005"  
  #   networks:
  #     - dev_network 

  # reportservices:
  #   build: ./reportservices
  #   container_name: microservices_container_reportservices
  #   ports:
  #     - "8006:8006"
  #   expose:
  #   - "8006"
  #   networks:
  #     - dev_network

  # subscriptionservices:
  #   build: ./subscriptionservices
  #   container_name: microservices_container_subscriptionservices
  #   ports:
  #     - "8007:8007"
  #   expose:
  #   - "8007"
  #   networks:
  #     - dev_network

  voucherservices:
    build: ./voucherservices
    container_name: reseller_admin_backend_voucherservices
    ports:
      - "8008:8008"
    expose:
    - "8008"
    networks:
      - dev_network  
    volumes:
      - ./voucherservices:/voucherservices
      - '/voucherservices/node_modules'
    
  
networks:
  dev_network:
    driver: bridge