version: "3.8"
services:
  main:
    build: ./microfrontends/main
    container_name: microfrontend_container_main
    ports:
    - 3000:3000
    networks:
    - dev_network
    depends_on:
    - customer
    - api-gateway
  customer:
    build: ./microfrontends/customer
    container_name: microfrontend_container_customer
    ports:
    - 3001:3001
    networks:
    - dev_network
    depends_on:
    - api-gateway
  api-gateway:
    build: ./microservices/api-gateway
    container_name: microservices_container_api-gateway
    ports:
    - 8000:8000
    expose:
    - "8000"
    networks:
    - dev_network
    depends_on:
    - adminservices
    - customerservices
  adminservices:
    build: ./microservices/adminservices
    container_name: microservices_container_adminservices
    ports:
    - 8001:8001
    expose:
    - "8001"
    networks:
    - dev_network
  customerservices:
    build: ./microservices/customerservices
    container_name: microservices_container_customerservices
    ports:
    - 8002:8002
    expose:
    - "8002"
    networks:
    - dev_network
networks:
  dev_network:
    driver: bridge