apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendadmin-admin-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backendadmin-admin-service
  template:
    metadata:
      labels:
        app: backendadmin-admin-service
    spec:
      containers:
      - name: backendadmin-admin-service
        image: hordansodevops/reseller_admin_backend_adminservices:latest
        ports:
        - containerPort: 8001
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: adminservices-config