apiVersion: v1
kind: Service
metadata:
  name: adminbackend-adminapi-ingress
spec:
  selector:
    app: adminbackend-adminapi-ingress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
