apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminbackend-adminapi-ingress
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adminbackend-adminapi-ingress
  template:
    metadata:
      labels:
        app: adminbackend-adminapi-ingress
    spec:
      containers:
      - name: adminbackend-adminapi-ingress
        image: hordansodevops/reseller_admin_backend_adminservices:latest
        ports:
        - containerPort: 8001
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: adminservices-config