apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendadmin-api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backendadmin-api-service
  template:
    metadata:
      labels:
        app: backendadmin-api-service
    spec:
      containers:
      - name: backendadmin-api-service
        image: hordansodevops/reseller_admin_backend_api:latest
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: api-config