apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminbackend-customerapi-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminbackend-customerapi-service
  template:
    metadata:
      labels:
        app: adminbackend-customerapi-service
    spec:
      containers:
      - name: adminbackend-customerapi-service
        image: hordansodevops/reseller_admin_backend_customerservices:latest
        ports:
        - containerPort: 8002
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: customerservices-config